---
apiVersion: v1
kind: Service
metadata:
 name: result-app-service
 labels: 
   author: saketh
spec:
 type: LoadBalancer
 selector: 
  name: voting-result
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30009
...

