---
apiVersion: v1
kind: Service
metadata: 
 name: voting-app-service
 labels:
  author: saketh
spec:
 type: LoadBalancer
 selector: 
  name: voting-app
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
...
